Repository Dopamine-Detoxx/Brain-Cleaner, pull requests merged in 2025-04, with the labels that each got.

#91 [FEAT] 댓글, 대댓글 기능
  be/src/main/java/com/dd/blog/domain/post/comment/controller/ApiV1CommentController.java
  be/src/main/java/com/dd/blog/domain/post/comment/dto/CommentRequestDto.java
  be/src/main/java/com/dd/blog/domain/post/comment/dto/CommentResponseDto.java
  be/src/main/java/com/dd/blog/domain/post/comment/dto/CommentUpdateResponseDto.java
  be/src/main/java/com/dd/blog/domain/post/comment/entity/Comment.java
  be/src/main/java/com/dd/blog/domain/post/comment/repository/CommentRepository.java
  be/src/main/java/com/dd/blog/domain/post/comment/service/CommentService.java
  be/src/main/java/com/dd/blog/global/exception/GlobalExceptionHandler.java
Labels: 🧠 merge feature

#96 [FEATURE] 게시글 - 좋아요 기능 구현 및 FE
  be/src/main/java/com/dd/blog/domain/post/post/entity/Post.java
  be/src/main/java/com/dd/blog/domain/post/postlike/controller/ApiV1PostLikeController.java
  be/src/main/java/com/dd/blog/domain/post/postlike/service/PostLikeService.java
  fe/src/app/page.tsx
  fe/src/components/Post.tsx
Labels: 🧠 feature

#101 [FIX] 인증게시물 - 숫자만 보이고 시간은 안 보이는 문제 해결
  be/src/main/java/com/dd/blog/domain/post/post/controller/ApiV1PostController.java
  be/src/main/java/com/dd/blog/domain/post/post/dto/PostRequestDto.java
  be/src/main/java/com/dd/blog/domain/post/post/service/PostService.java
  fe/package-lock.json
  fe/package.json
  fe/src/app/verification/write/page.tsx
  fe/src/components/Post.tsx
Labels: 🐞 bug

#120 [REFACTOR] 댓글 작성: [FE]에서 userId 넘기는 구조 TO [BE] @AuthenticationPrincipal로 받기
  be/src/main/java/com/dd/blog/domain/post/comment/controller/ApiV1CommentController.java
  be/src/main/java/com/dd/blog/domain/post/comment/service/CommentService.java
  fe/src/app/page.tsx
  fe/src/components/Post.tsx
Labels: 🔄 refactor

#122 [FEAT/FIX] (FE)댓글 - UI 구현 + (BE)댓글 수·디톡스 시간 - 출력 버그 수정
  be/src/main/java/com/dd/blog/domain/post/post/dto/PostResponseDto.java
  be/src/main/java/com/dd/blog/domain/post/post/entity/Post.java
  be/src/main/java/com/dd/blog/domain/post/post/service/PostService.java
  fe/src/app/page.tsx
  fe/src/components/CommentModal.tsx
  fe/src/components/Post.tsx
  fe/src/types/comment.ts
Labels: 🐞 bug, 🧠 feature

#125 [FEAT] 관리자 승인 페이지 및 백엔드 연동 완료
  be/src/main/java/com/dd/blog/domain/admin/controller/AdminDashboardController.java
  be/src/main/java/com/dd/blog/domain/admin/controller/AdminVerificationV1Controller.java
  be/src/main/java/com/dd/blog/domain/admin/dto/AdminDashboardStatsDto.java
  be/src/main/java/com/dd/blog/domain/admin/service/AdminDashboardService.java
  be/src/main/java/com/dd/blog/domain/admin/service/AdminVerificationService.java
  be/src/main/java/com/dd/blog/domain/post/post/repository/PostRepository.java
  be/src/main/java/com/dd/blog/domain/post/post/service/PostService.java
  be/src/main/java/com/dd/blog/domain/post/verification/dto/VerificationRequestDto.java
  be/src/main/java/com/dd/blog/domain/post/verification/dto/VerificationResponseDto.java
  be/src/main/java/com/dd/blog/domain/post/verification/repository/VerificationRepository.java
  be/src/main/java/com/dd/blog/domain/user/user/repository/UserRepository.java
  fe/package-lock.json
  fe/package.json
  fe/src/app/admin/approvals/page.tsx
  fe/src/app/admin/layout.tsx
  fe/src/app/admin/page.tsx
  fe/src/app/admin/users/[userId]/page.tsx
  fe/src/app/admin/verifications/page.tsx
  fe/src/app/layout.tsx
  fe/src/app/page.tsx
  fe/src/components/Post.tsx
Labels: 🧠 feature

#132 [FEAT] 공지사항 게시판 구현
  be/src/main/java/com/dd/blog/domain/post/post/service/PostService.java
  be/src/main/java/com/dd/blog/global/init/CategoryInitializer.java
  fe/src/app/page.tsx
  fe/src/app/post/write/page.tsx
Labels: 🧠 merge feature

#131 [FEAT] 프로필페이지 - 팔로우/언팔로우, 팔로우목록조회
  be/src/main/java/com/dd/blog/domain/user/follow/controller/ApiV1FollowerController.java
  be/src/main/java/com/dd/blog/domain/user/follow/dto/FollowUserDto.java
  be/src/main/java/com/dd/blog/domain/user/follow/service/FollowService.java
  fe/src/app/profile/[id]/page.tsx
  fe/src/app/profile/me/page.tsx
Labels: 🧠 feature

#137 [FEATURE] 포인트상점 BE 전체, PointItemInitializer로 데이터 대입
  be/src/main/java/com/dd/blog/domain/point/pointstore/controller/PointStoreController.java
  be/src/main/java/com/dd/blog/domain/point/pointstore/dto/PointItemPurchaseListDto.java
  be/src/main/java/com/dd/blog/domain/point/pointstore/dto/PointItemPurchaseRequestDto.java
  be/src/main/java/com/dd/blog/domain/point/pointstore/dto/PointItemPurchaseResultDto.java
  be/src/main/java/com/dd/blog/domain/point/pointstore/dto/PointItemResponseDto.java
  be/src/main/java/com/dd/blog/domain/point/pointstore/entity/PointItem.java
  be/src/main/java/com/dd/blog/domain/point/pointstore/entity/PointItemPurchase.java
  be/src/main/java/com/dd/blog/domain/point/pointstore/repository/PointItemPurchaseRepository.java
  be/src/main/java/com/dd/blog/domain/point/pointstore/repository/PointItemRepository.java
  be/src/main/java/com/dd/blog/domain/point/pointstore/service/PointStoreService.java
  be/src/main/java/com/dd/blog/global/init/PointItemInitializer.java
Labels: 🧠 merge feature
